### ISSUE TITLE
Not clear how to get current collection length

### ISSUE THREAD

**Issue by serby** [bengourley/chale#4]
`collection.models.length`?
`collection.slice().length`?

Should it not be:
`collection.length`

**Comment by bengourley** [comment]
why would you need to slice? We could add a getter I suppose. PR welcome or I will get around to it at some point.

**Comment by serby** [comment]
`slice()` already exists and was the easiest way I could it to an array to get the length. Reaching and getting models seems weird when it already behaves like a collection already.

**Comment by bengourley** [comment]
ah I see, you sliced the `collection` and not `collection.models`. Yeah I agree we should add `.length`.
